In [4]:
import numpy as np

In [5]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [6]:
sample_array = np.array([[0] * (20) for _ in range(30)])
sample_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
range_array = np.array([1,2,3,4,5])
range_array

array([1, 2, 3, 4, 5])

In [9]:
np.random.random((5,3))

array([[0.993352  , 0.26417204, 0.43789206],
       [0.20151223, 0.47671665, 0.40728599],
       [0.34826341, 0.53751987, 0.97789757],
       [0.50798766, 0.32852449, 0.91553147],
       [0.60566735, 0.65691768, 0.17408536]])

In [10]:
np.random.seed(2)
random_array_2 = np.random.randint(10, size = (5,3))
random_array_2

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [11]:
np.unique(random_array_2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
ones = np.ones(3)
ones 

array([1., 1., 1.])

In [13]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [14]:
ones + a1

array([2., 3., 4.])

In [16]:
massive_array = np.random.random(1000)


In [19]:
massive_array[:10]

array([0.37207537, 0.14515563, 0.39557349, 0.16430447, 0.538219  ,
       0.17835428, 0.04904435, 0.61433922, 0.38100549, 0.68347489])

In [21]:
%timeit
sum(massive_array)

np.float64(486.4879474452775)