In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [4]:
sample_array = np.array([[0] * (20) for _ in range(30)])
sample_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [5]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
range_array = np.array([1,2,3,4,5])
range_array

array([1, 2, 3, 4, 5])

In [7]:
np.random.random((5,3))

array([[0.31502254, 0.85300142, 0.46425989],
       [0.5341014 , 0.92752828, 0.8162588 ],
       [0.96083284, 0.7062436 , 0.5375287 ],
       [0.96948827, 0.72141861, 0.91413566],
       [0.44619265, 0.20488046, 0.06320688]])

In [8]:
np.random.seed(2)
random_array_2 = np.random.randint(10, size = (5,3))
random_array_2

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [9]:
np.unique(random_array_2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
ones = np.ones(3)
ones 

array([1., 1., 1.])

In [11]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [12]:
ones + a1

array([2., 3., 4.])

In [13]:
massive_array = np.random.random(1000)


In [14]:
massive_array[:10]

array([0.51357812, 0.18443987, 0.78533515, 0.85397529, 0.49423684,
       0.84656149, 0.07964548, 0.50524609, 0.0652865 , 0.42812233])

In [15]:
%timeit sum(massive_array)
%timeit massive_array.sum()

68.9 μs ± 4.17 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.49 μs ± 49.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [17]:
np.var(high_var_array) low_var_array)

TypeError: only integer scalar arrays can be converted to a scalar index