# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [133]:
# Import NumPy as its abbreviation 'np'
import numpy as np
np

<module 'numpy' from '/Users/pawn/Desktop/firstCondaProject/env/lib/python3.13/site-packages/numpy/__init__.py'>

In [134]:
# Create a 1-dimensional NumPy array using np.array()
arr1 =np.array([0,0,0,0])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[0,0,0,0],
               [0,0,0,0]])
arr2


# Create a 3-dimensional Numpy array using np.array()
#arr3 = np.array([
   #layer 0 [[0,0,0,0],
 #   [0,0,0,0]],
    #layer 1 [[0,0,0,0],
 #   [0,0,0,0]],
    #layer 2 [[0,0,0,0],
 #   [0,0,0,0]]
#])

arr3 = np.array([
    [[0,0,0,0],
    [0,0,0,0]], #layer 0
    [[0,0,0,0],
    [0,0,0,0]], #layer 1
    [[0,0,0,0],
    [0,0,0,0]] #layer 2
])
arr1,arr2,arr3



(array([0, 0, 0, 0]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [135]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)


In [136]:
# Attributes of 2-dimensional array


In [137]:
# Attributes of 3-dimensional array


In [138]:
# CLARIFICATION: What makes an array 3D?
# It's NOT about having "3 sublists" - it's about having 3 DIMENSIONS!

print("=== DIMENSION vs NESTED LISTS ===")
print()

# Example 1: Different 3D arrays with different numbers of "sublists"
print("1. A 3D array with 2 'layers':")
small_3d = np.array([
    [[1, 2], [3, 4]],  # Layer 0
    [[5, 6], [7, 8]]   # Layer 1
])
print(f"Shape: {small_3d.shape} = (2 layers, 2 rows, 2 columns)")
print(small_3d)
print()

print("2. A 3D array with 4 'layers':")
big_3d = np.array([
    [[1, 2, 3]],    # Layer 0: 1 row, 3 columns
    [[4, 5, 6]],    # Layer 1: 1 row, 3 columns  
    [[7, 8, 9]],    # Layer 2: 1 row, 3 columns
    [[10, 11, 12]]  # Layer 3: 1 row, 3 columns
])
print(f"Shape: {big_3d.shape} = (4 layers, 1 row, 3 columns)")
print(big_3d)
print()

print("3. A 3D array with just 1 'layer':")
single_layer_3d = np.array([
    [[1, 2, 3, 4, 5]]  # Just 1 layer, 1 row, 5 columns
])
print(f"Shape: {single_layer_3d.shape} = (1 layer, 1 row, 5 columns)")
print(single_layer_3d)
print()

print("=== THE KEY POINT ===")
print("ALL of these are 3D arrays because they have 3 DIMENSIONS in their shape:")
print("- Dimension 1: Number of layers (depth/Z-axis)")
print("- Dimension 2: Number of rows (height/Y-axis)") 
print("- Dimension 3: Number of columns (width/X-axis)")
print()
print("A 3D array can have ANY number of layers, rows, or columns!")
print("What makes it 3D is that you need 3 coordinates [layer, row, column] to access any element.")


=== DIMENSION vs NESTED LISTS ===

1. A 3D array with 2 'layers':
Shape: (2, 2, 2) = (2 layers, 2 rows, 2 columns)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

2. A 3D array with 4 'layers':
Shape: (4, 1, 3) = (4 layers, 1 row, 3 columns)
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]

3. A 3D array with just 1 'layer':
Shape: (1, 1, 5) = (1 layer, 1 row, 5 columns)
[[[1 2 3 4 5]]]

=== THE KEY POINT ===
ALL of these are 3D arrays because they have 3 DIMENSIONS in their shape:
- Dimension 1: Number of layers (depth/Z-axis)
- Dimension 2: Number of rows (height/Y-axis)
- Dimension 3: Number of columns (width/X-axis)

A 3D array can have ANY number of layers, rows, or columns!
What makes it 3D is that you need 3 coordinates [layer, row, column] to access any element.


In [139]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

0  1  2  3
0  0  0  0  0
1  0  0  0  0

In [140]:
# Create an array of shape (10, 2) with only ones
one_arr = np.ones((10,2))
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [141]:
# Create an array of shape (7, 2, 3) of only zeros
zero_arr = np.zeros((7,2,3))
zero_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [142]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0,100,3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [143]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
range_arr = np.random.randint(0,10,(7,2))
range_arr

array([[6, 1],
       [3, 8],
       [1, 9],
       [8, 9],
       [4, 1],
       [3, 6],
       [7, 2]])

In [144]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
range_arr = np.random.rand(3,5)
range_arr

array([[0.9093204 , 0.25877998, 0.66252228, 0.31171108, 0.52006802],
       [0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894],
       [0.89482735, 0.59789998, 0.92187424, 0.0884925 , 0.19598286]])

In [145]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr = np.random.randint(0,10,(4,6))
random_arr


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [146]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(42)

random_arr = np.random.randint(1,10,(3,7))
random_arr


# Find the unique numbers in the array you just created
unique_arr = np.unique(random_arr)
unique_arr
random_arr


array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6],
       [5, 2, 8, 6, 2, 5, 1]])

In [147]:
# Find the 0'th index of the latest array you created
random_arr[0][0]



np.int64(7)

In [148]:
# Get the first 2 rows of latest array you created
random_arr[0],random_arr[1]


(array([7, 4, 8, 5, 7, 3, 7]), array([8, 5, 4, 8, 8, 3, 6]))

In [149]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[0][0:2],random_arr[1][0:2]


(array([7, 4]), array([8, 5]))

In [150]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr1 = np.random.randint(0,10,(3,5))
random_arr2 = np.ones((3,5))


In [151]:
# Add the two arrays together
arr3 = random_arr1 + random_arr2
arr3

array([[10.,  6.,  9.,  1., 10.],
       [ 3.,  7.,  4.,  9.,  3.],
       [ 5.,  3.,  7.,  5.,  9.]])

In [152]:
# Create another array of ones of shape (5, 3)
random_arr = np.ones((5,3))

In [153]:
# Try add the array of ones and the other most recent array together
arr3.shape,random_arr.shape
random_arr_tranposed = random_arr.T
new_arr = arr3 + random_arr_tranposed

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [154]:
# Create another array of ones of shape (3, 5)
random_arr = np.ones((3,5))
random_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
# Subtract the new array of ones from the other most recent array
new_arrTwo = random_arr - new_arr
new_arrTwo

array([[-10.,  -6.,  -9.,  -1., -10.],
       [ -3.,  -7.,  -4.,  -9.,  -3.],
       [ -5.,  -3.,  -7.,  -5.,  -9.]])

In [158]:
# Multiply the ones array with the latest array
latest_arr = new_arrTwo * random_arr

In [159]:
# Take the latest array to the power of 2 using '**'
latest_arr **2

array([[100.,  36.,  81.,   1., 100.],
       [  9.,  49.,  16.,  81.,   9.],
       [ 25.,   9.,  49.,  25.,  81.]])

In [161]:
# Do the same thing with np.square()
np.square(latest_arr)

array([[100.,  36.,  81.,   1., 100.],
       [  9.,  49.,  16.,  81.,   9.],
       [ 25.,   9.,  49.,  25.,  81.]])

In [162]:
# Find the mean of the latest array using np.mean()
np.mean(latest_arr)

np.float64(-6.066666666666666)

In [163]:
# Find the maximum of the latest array using np.max()
np.max(latest_arr)

np.float64(-1.0)

In [164]:
# Find the minimum of the latest array using np.min()
np.min(latest_arr)

np.float64(-10.0)

In [165]:
# Find the standard deviation of the latest array
np.std(latest_arr)

np.float64(2.815828277592383)

In [166]:
# Find the variance of the latest array
np.var(latest_arr)

np.float64(7.9288888888888875)

In [169]:
# Reshape the latest array to (3, 5, 1)
reshape_latest = np.reshape(latest_arr, (3,5,1))

In [170]:
# Transpose the latest array
reshape_latest.T

array([[[-10.,  -3.,  -5.],
        [ -6.,  -7.,  -3.],
        [ -9.,  -4.,  -7.],
        [ -1.,  -9.,  -5.],
        [-10.,  -3.,  -9.]]])

What does the transpose do?

In [172]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
one_to_ten_one = np.random.randint(0,10, (3,3))
one_to_ten_two = np.random.randint(0,10, (3,2))

In [173]:
# Perform a dot product on the two newest arrays you created
np.dot(one_to_ten_one,one_to_ten_two)

array([[72, 34],
       [31, 17],
       [77, 29]])

In [174]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
one_to_ten_three = np.random.randint(0,10, (4,3))
one_to_ten_four = np.random.randint(0,10, (4,3))

In [175]:
# Perform a dot product on the two newest arrays you created
np.dot(one_to_ten_three, one_to_ten_four)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [ ]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='


In [ ]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.